alldata <- read.table("../household_power_consumption.txt",header=TRUE, sep=";", na.strings='?')
mydata <- subset(alldata, as.Date(alldata$Date, format="%d/%m/%Y") %in% c(as.Date("2007-02-01"),as.Date("2007-02-02")))
png("plot3.png")
par(bg="transparent")
plot(strptime(paste(mydata$Date,mydata$Time), format="%d/%m/%Y %H:%M:%S"), mydata$Sub_metering_1, 
     xlab="", ylab="Energy Sub metering", type="n")
lines(strptime(paste(mydata$Date,mydata$Time), format="%d/%m/%Y %H:%M:%S"), mydata$Sub_metering_1)
lines(strptime(paste(mydata$Date,mydata$Time), format="%d/%m/%Y %H:%M:%S"), mydata$Sub_metering_2, col="red")
lines(strptime(paste(mydata$Date,mydata$Time), format="%d/%m/%Y %H:%M:%S"), mydata$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lwd=1)
dev.off()
